[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node scripts/clone-repos.js && node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
