[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd observatory && npm install"]

[phases.build]
cmds = ["cd observatory && npm run build"]

[start]
cmd = "cd observatory && node build/index.js"
