apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: ai-dawg
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-dawg
      component: backend
  template:
    metadata:
      labels:
        app: ai-dawg
        component: backend
    spec:
      containers:
      - name: backend
        image: ai-dawg-backend:latest
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: jarvis-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: jarvis-secrets
              key: redis-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
