apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    app: ai-dawg
    component: producer
spec:
  type: ClusterIP
  selector:
    app: ai-dawg
    component: producer
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
