apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: ai-dawg
    component: producer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-dawg
      component: producer
  template:
    metadata:
      labels:
        app: ai-dawg
        component: producer
    spec:
      containers:
      - name: producer
        image: ai-dawg-producer:latest
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: PORT
          value: "8001"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
