apiVersion: v1
kind: ConfigMap
metadata:
  name: jarvis-config
  namespace: production
  labels:
    app: jarvis-api
data:
  # Application Configuration
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"

  # AWS Configuration
  aws-region: "us-east-1"
  s3-bucket: "jarvis-production-storage"

  # Feature Flags
  FEATURE_AI_AGENTS: "true"
  FEATURE_MUSIC_STUDIO: "true"
  FEATURE_FREESTYLE: "true"
  FEATURE_BUSINESS_ASSISTANT: "true"

  # Rate Limiting
  RATE_LIMIT_WINDOW_MS: "60000"
  RATE_LIMIT_MAX_REQUESTS: "100"

  # Cache Configuration
  CACHE_TTL: "3600"
  CACHE_MAX_ITEMS: "1000"

  # Monitoring
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "true"
  METRICS_PORT: "9090"

  # Application URLs
  API_BASE_URL: "https://api.jarvis-ai.app"
  WEB_BASE_URL: "https://jarvis-ai.app"
  WEBSOCKET_URL: "wss://api.jarvis-ai.app"

  # CORS Origins
  CORS_ORIGINS: "https://jarvis-ai.app,https://www.jarvis-ai.app"

  # Session Configuration
  SESSION_COOKIE_SECURE: "true"
  SESSION_COOKIE_SAME_SITE: "strict"
  SESSION_MAX_AGE: "86400000"

  # File Upload
  MAX_FILE_SIZE: "52428800"
  ALLOWED_FILE_TYPES: "image/jpeg,image/png,image/gif,application/pdf,audio/mpeg,audio/wav"

  # Database
  DB_POOL_MIN: "2"
  DB_POOL_MAX: "10"
  DB_CONNECTION_TIMEOUT: "30000"
  DB_IDLE_TIMEOUT: "10000"

  # Redis
  REDIS_MAX_RETRIES: "3"
  REDIS_RETRY_DELAY: "1000"

  # External Services
  OPENAI_MODEL: "gpt-4-turbo-preview"
  ANTHROPIC_MODEL: "claude-3-5-sonnet-20241022"
  OPENAI_MAX_TOKENS: "4000"
  ANTHROPIC_MAX_TOKENS: "4000"

  # Email
  SMTP_HOST: "email-smtp.us-east-1.amazonaws.com"
  SMTP_PORT: "587"
  EMAIL_FROM: "noreply@jarvis-ai.app"

  # Backup
  BACKUP_ENABLED: "true"
  BACKUP_RETENTION_DAYS: "30"
  BACKUP_SCHEDULE: "0 2 * * *"
