[build]
  command = "npm run build:shared && npm run build:frontend"
  publish = "packages/frontend/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  included_files = ["packages/shared/dist/**"]

# NOTE: Set these environment variables in Netlify Dashboard
# Dashboard -> Site Settings -> Environment Variables
# DO NOT commit real API keys to version control!

[context.production.environment]
  # Frontend
  VITE_SUPABASE_URL = "your-supabase-url"
  VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key"
  VITE_BACKEND_URL = "your-backend-url"

  # Backend (Netlify Functions)
  FRONTEND_URL = "your-frontend-url"
  SUPABASE_URL = "your-supabase-url"
  SUPABASE_ANON_KEY = "your-supabase-anon-key"
  SUPABASE_SERVICE_KEY = "your-supabase-service-key"

  # Twitter OAuth
  TWITTER_OAUTH_CLIENT_ID = "your-twitter-oauth-client-id"
  TWITTER_OAUTH_CLIENT_SECRET = "your-twitter-oauth-client-secret"

  # Twitter Legacy API
  TWITTER_API_KEY = "your-twitter-api-key"
  TWITTER_API_SECRET = "your-twitter-api-secret"
  TWITTER_ACCESS_TOKEN = "your-twitter-access-token"
  TWITTER_ACCESS_TOKEN_SECRET = "your-twitter-access-token-secret"

  # Stripe
  STRIPE_SECRET_KEY = "your-stripe-secret-key"
  STRIPE_WEBHOOK_SECRET = "your-stripe-webhook-secret"
  STRIPE_STARTER_PRICE_ID = "your-stripe-starter-price-id"
  STRIPE_PRO_PRICE_ID = "your-stripe-pro-price-id"
  STRIPE_ENTERPRISE_PRICE_ID = "your-stripe-enterprise-price-id"
