apiVersion: v1
kind: ServiceAccount
metadata:
  name: jarvis-sa
  namespace: jarvis
  labels:
    app: jarvis-control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jarvis-role
  namespace: jarvis
rules:
  # Allow reading ConfigMaps and Secrets
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  
  # Allow managing pods (for autonomous service management)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Allow reading services
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  
  # Allow reading deployments (for health checks)
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jarvis-rolebinding
  namespace: jarvis
subjects:
  - kind: ServiceAccount
    name: jarvis-sa
    namespace: jarvis
roleRef:
  kind: Role
  name: jarvis-role
  apiGroup: rbac.authorization.k8s.io
---
# Cross-namespace permissions to manage AI DAWG services
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jarvis-ai-dawg-role
  namespace: ai-dawg
rules:
  # Allow managing AI DAWG services
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jarvis-ai-dawg-rolebinding
  namespace: ai-dawg
subjects:
  - kind: ServiceAccount
    name: jarvis-sa
    namespace: jarvis
roleRef:
  kind: Role
  name: jarvis-ai-dawg-role
  apiGroup: rbac.authorization.k8s.io
