apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-brain
  labels:
    app: ai-dawg
    component: ai-brain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-dawg
      component: ai-brain
  template:
    metadata:
      labels:
        app: ai-dawg
        component: ai-brain
    spec:
      containers:
      - name: ai-brain
        image: ai-dawg-ai-brain:latest
        ports:
        - containerPort: 8002
          name: http
        env:
        - name: PORT
          value: "8002"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 5
