apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: ai-dawg
    component: backend
spec:
  type: ClusterIP
  selector:
    app: ai-dawg
    component: backend
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
