apiVersion: v1
kind: Service
metadata:
  name: jarvis
  labels:
    app: jarvis
spec:
  type: LoadBalancer
  selector:
    app: jarvis
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
