name: JarvisApp
options:
  bundleIdPrefix: com.benkennon
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

settings:
  PRODUCT_NAME: JarvisApp
  PRODUCT_BUNDLE_IDENTIFIER: com.benkennon.jarvis
  SWIFT_VERSION: "5.9"
  TARGETED_DEVICE_FAMILY: "1"
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"
  DEVELOPMENT_TEAM: ""

targets:
  JarvisApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: JarvisApp
        excludes:
          - "*.md"
    info:
      path: JarvisApp/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleDisplayName: Jarvis
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "Jarvis needs microphone access for voice commands and audio recording."
        NSContactsUsageDescription: "Jarvis needs access to contacts for personalized assistance."
        NSCalendarsUsageDescription: "Jarvis needs access to calendar for scheduling assistance."
        NSBluetoothAlwaysUsageDescription: "Jarvis uses Bluetooth for device connectivity."
        UIBackgroundModes:
          - audio
          - fetch
          - processing
          - remote-notification
    settings:
      INFOPLIST_FILE: JarvisApp/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      ENABLE_PREVIEWS: true
      DEVELOPMENT_ASSET_PATHS: '"JarvisApp/Preview Content"'
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
    scheme:
      testTargets: []
      gatherCoverageData: false
      environmentVariables:
        - variable: BACKEND_URL
          value: wss://control-plane-production-e966.up.railway.app
          isEnabled: true
    preBuildScripts: []
    postBuildScripts: []
    dependencies: []

schemes:
  JarvisApp:
    build:
      targets:
        JarvisApp: all
    run:
      config: Debug
      environmentVariables:
        - variable: BACKEND_URL
          value: wss://control-plane-production-e966.up.railway.app
          isEnabled: true
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
