[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npx tsx src/main.ts"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
