apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jarvis-data-pvc
  namespace: jarvis
  labels:
    app: jarvis-control-plane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Change based on cloud provider (gp3, pd-ssd, etc.)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jarvis-logs-pvc
  namespace: jarvis
  labels:
    app: jarvis-control-plane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
