apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

replicas:
  - name: jarvis
    count: 3
  - name: backend
    count: 2
  - name: vocal-coach
    count: 2
  - name: producer
    count: 2
  - name: ai-brain
    count: 2
