apiVersion: v1
kind: Service
metadata:
  name: jarvis-api
  namespace: production
  labels:
    app: jarvis-api
    tier: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: ClusterIP
  selector:
    app: jarvis-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: jarvis-api-headless
  namespace: production
  labels:
    app: jarvis-api
    tier: backend
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: jarvis-api
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
